export const FETCH_VIDEOGAMES = "FETCH_VIDEOGAMES" 
export const FETCH_BY_ID = "FETCH_BY_ID"
export const FETCH_BY_NAME = "FETCH_BY_NAME" 
export const CLEAN_DETAIL = "CLEAN_DETAIL"
export const SET_SELECTED_ORDER = "SET_SELECTED_ORDER"
export const SET_SELECTED_FILTERS = "SET_SELECTED_FILTERS"
export const FILTER_BY_ALPHA = "FILTER_BY_ALPHA"
export const FILTER_BY_GENRE = "FILTER_BY_GENRE"
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN"
export const FILTER_BY_RATING = "FILTER_BY_RATING"
export const SAVE_VIDEOGAME = "SAVE_VIDEOGAME"
export const REMOVE_SAVED_VIDEOGAME = "REMOVE_SAVED_VIDEOGAME"
export const DESTROY_VIDEOGAME = 'DESTROY_VIDEOGAME';

